name: Slack Cleaner
on:
  schedule:
  - cron:  '0 0 * * *'
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install slack-cleaner2
        run: pip install slack-cleaner2
      - name: Run slack-cleaner2
        run: python3 clean_journal.py ${{ secrets.SLACK_LEGACY_TOKEN }}
